RWSPU-7: resolved several issues and added OpenMRS license

diff --git a/openmrs-emt/usr/local/bin/openmrs-emt b/openmrs-emt/usr/local/bin/openmrs-emt
--- a/openmrs-emt/usr/local/bin/openmrs-emt
+++ b/openmrs-emt/usr/local/bin/openmrs-emt
@@ -1,12 +1,6 @@
 #!/bin/bash
 
-# Important variables
 EMT_DIR=/usr/local/etc/EmrMonitoringTool
-OPENMRS_APP_NAME=$1
-OPENMRS_DATA_DIR=$2
-TOMCAT_ROOT_URL=$3
-OPENMRS_URL=$TOMCAT_ROOT_URL/$OPENMRS_APP_NAME
-EMT_MAIN_CONFIG=$EMT_DIR/."$OPENMRS_APP_NAME"-emt-config.properties
 
 if [ "$1" == "-pushToDHIS" ]; then
 	if [ "$#" -ne 1 ]; then
@@ -80,6 +74,16 @@ elif [ "$1" == "-copyLocalReportsTo" ]; then
 		cp $REPORT $2
 	done
 	exit 1
+elif [ "$1" == "-reconfigure" ]; then
+	if [ "$#" -ne 4 ]; then
+		echo "Illegal number of parameters"
+		echo "Usage:  openmrs-emt -reconfigure <OpenMRS APPName> <OpenMRS Data Directory> <Tomcat Root URL>"
+		echo ""
+		echo "Usage example: openmrs-emt -reconfigure openmrs167 ~/.OpenMRS http://localhost:8080"
+		echo ""
+		exit 1
+	fi
+	rm $EMT_DIR/."$2"-emt-config.properties
 elif [ "$#" -ne 3 ]; then
 	echo "Illegal number of parameters"
 	echo "Usage:  openmrs-emt <OpenMRS APPName> <OpenMRS Data Directory> <Tomcat Root URL>"
@@ -89,19 +93,59 @@ elif [ "$#" -ne 3 ]; then
 	exit 1
 fi
 
+if [ "$1" == "-reconfigure" ]
+	then
+		OPENMRS_APP_NAME=$2
+		OPENMRS_DATA_DIR=$3
+		TOMCAT_ROOT_URL=$4
+	else
+		OPENMRS_APP_NAME=$1
+		OPENMRS_DATA_DIR=$2
+		TOMCAT_ROOT_URL=$3
+fi
+OPENMRS_URL=$TOMCAT_ROOT_URL/$OPENMRS_APP_NAME
+EMT_MAIN_CONFIG=$EMT_DIR/."$OPENMRS_APP_NAME"-emt-config.properties
+
 if [ ! -d $EMT_DIR ]; then
 	mkdir $EMT_DIR
 fi
 
 if [ ! -f $EMT_MAIN_CONFIG ]; then
+echo "Do you want to configure DHIS server right now (Y/N): "
+read yesOrNo
+
+if [ "$yesOrNo" == "Y" ] || [ "$yesOrNo" == "Yes" ] || [ "$yesOrNo" == "YES" ] || [ "$yesOrNo" == "yes" ]
+	then
+		echo ""
+		echo "Enter DHIS Server URL: "; read DHIS_URL
+		echo "Enter DHIS Server Login UserName : "; read DHIS_USER
+		echo "Enter DHIS Server Login Password : "; stty -echo; read DHIS_PASS; stty echo;
+	
+		if [ $DHIS_URL == "" ] || [ $DHIS_USER == "" ] || [ $DHIS_PASS == "" ]; then
+			echo "DHIS URL, UserName and Password can't be empty and therefore DHIS Server configuration has been ignored"
+			DHIS_URL=""
+			DHIS_USER=""
+			DHIS_PASS=""
+		fi
+	else
+		echo "DHIS Server configuration has been ignored"
+		DHIS_URL=""
+		DHIS_USER=""
+		DHIS_PASS=""
+fi
+
+
 	cat <<EOF > $EMT_MAIN_CONFIG
 openmrs_app_name=$OPENMRS_APP_NAME
 openmrs_data_directory=$OPENMRS_DATA_DIR
 openmrs_backups_directory=$OPENMRS_DATA_DIR/backups
 openmrs_url=$OPENMRS_URL
+dhis_url=$DHIS_URL
+dhis_user=$DHIS_USER
+dhis_pass=$DHIS_PASS
 EOF
 	echo ""
-	echo "INFO: You can change the provided configurations by editing: $EMT_MAIN_CONFIG";
+	echo "INFO: You can change your provided configurations by editing: $EMT_MAIN_CONFIG";
 	echo ""
 fi
 
