RWSPU-10: Support for EMT to be installable to all Rwanda planned test sites requiring a fosid for each of them

diff --git a/openmrs-emt/usr/local/bin/openmrs-emt b/openmrs-emt/usr/local/bin/openmrs-emt
--- a/openmrs-emt/usr/local/bin/openmrs-emt
+++ b/openmrs-emt/usr/local/bin/openmrs-emt
@@ -67,7 +67,7 @@ elif [ "$1" == "-copyLocalReportsTo" ]; then
 		exit 1
 	fi
 	
-	EMT_REPORTS=($(find "$EMT_DIR"/shell-backend -name "*.pdf"))
+	EMT_REPORTS=($(find "$HOME" -name "emtReport_*.pdf"))
 	
 	for REPORT in "${EMT_REPORTS[@]}"
 	do
@@ -111,31 +111,28 @@ if [ ! -d "$EMT_DIR" ]; then
 fi
 
 if [ ! -f "$EMT_MAIN_CONFIG" ]; then
-echo "Do you want to configure DHIS server right now (Y/N): "
-read yesOrNo
+echo "Please enter fosaid or DHIS Organization unit code or Uniquely assigned ID for this server!!!"; read DHIS_ORG_FOSID
 
-if [ "$yesOrNo" == "y" ] || [ "$yesOrNo" == "Y" ] || [ "$yesOrNo" == "Yes" ] || [ "$yesOrNo" == "YES" ] || [ "$yesOrNo" == "yes" ]
-	then
-		echo ""
-		echo "Enter DHIS Server URL (eg. http://localhost:8080/dhis/api/dataValueSets): "; read DHIS_URL
-		echo "Enter DHIS Server Login UserName : "; read DHIS_USER
-		echo "Enter DHIS Server Login Password : "; stty -echo; read DHIS_PASS; stty echo;
-	
-		if [ "$DHIS_URL" == "" ] || [ "$DHIS_USER" == "" ] || [ "$DHIS_PASS" == "" ]; then
-			echo "DHIS URL, UserName and Password can't be empty and therefore DHIS Server configuration has been ignored"
-			DHIS_URL=""
-			DHIS_USER=""
-			DHIS_PASS=""
-		fi
-	else
-		echo "DHIS Server configuration has been ignored"
-		DHIS_URL=""
-		DHIS_USER=""
-		DHIS_PASS=""
+DHIS_ORG_UID=`sed '/^\#/d' "$EMT_DIR/emt-to-dhis-mapping.txt" | grep '$DHIS_ORG_FOSID' | tail -n 1 | cut -d "=" -f2-`
+
+if [ "$DHIS_ORG_FOSID" == "" ] || [ "$DHIS_ORG_UID" == "" ]
+	echo "fosid for this Server is Required to configure this tool (Ask from the tool providers if you are not sure what this is or add a new mapping at $EMT_DIR/emt-to-dhis-mapping.txt)"
+	exit 1
 fi
 
+echo ""
+echo "Enter DHIS Server DataValueSets API URL (eg. http://localhost:8080/dhis/api/dataValueSets): "; read DHIS_URL
+echo "Enter DHIS Server Login UserName : "; read DHIS_USER
+echo "Enter DHIS Server Login Password : "; stty -echo; read DHIS_PASS; stty echo;
+	
+if [ "$DHIS_URL" == "" ] || [ "$DHIS_USER" == "" ] || [ "$DHIS_PASS" == "" ]; then
+	echo "DHIS URL, UserName and Password can't be empty and therefore DHIS Server configuration has been ignored"
+	DHIS_URL=""
+	DHIS_USER=""
+	DHIS_PASS=""
+fi
 
-	cat <<EOF > $EMT_MAIN_CONFIG
+cat <<EOF > $EMT_MAIN_CONFIG
 openmrs_app_name=$OPENMRS_APP_NAME
 openmrs_data_directory=$OPENMRS_DATA_DIR
 openmrs_backups_directory=$OPENMRS_DATA_DIR/backups
@@ -143,6 +140,7 @@ openmrs_url=$OPENMRS_URL
 dhis_url=$DHIS_URL
 dhis_user=$DHIS_USER
 dhis_pass=$DHIS_PASS
+dhis_org_unit_uid=$DHIS_ORG_UID
 EOF
 	echo ""
 	echo "INFO: You can change your provided configurations by editing: $EMT_MAIN_CONFIG";
