RWSPU-8: supporting multiple MoH EMR instances via separate configuration files for each

diff --git a/openmrs-emt/usr/local/bin/openmrs-emt b/openmrs-emt/usr/local/bin/openmrs-emt
--- a/openmrs-emt/usr/local/bin/openmrs-emt
+++ b/openmrs-emt/usr/local/bin/openmrs-emt
@@ -1,12 +1,12 @@
 #!/bin/bash
 
 if [ "$#" -ne 3 ]; then
-echo "Illegal number of parameters"
-echo "Usage:  improved-installation.sh <OpenMRS APPName> <OpenMRS Data Directory> <Tomcat Root URL>"
-echo ""
-echo "Usage example: improved-installation.sh openmrs167 ~/.OpenMRS http://localhost:8080"
-echo ""
-exit 1
+	echo "Illegal number of parameters"
+	echo "Usage:  improved-installation.sh <OpenMRS APPName> <OpenMRS Data Directory> <Tomcat Root URL>"
+	echo ""
+	echo "Usage example: improved-installation.sh openmrs167 ~/.OpenMRS http://localhost:8080"
+	echo ""
+	exit 1
 fi
 
 # Important variables
@@ -15,22 +15,22 @@ OPENMRS_APP_NAME=$1
 OPENMRS_DATA_DIR=$2
 TOMCAT_ROOT_URL=$3
 OPENMRS_URL=$TOMCAT_ROOT_URL/$OPENMRS_APP_NAME
-EMT_MAIN_CONFIG=$EMT_DIR/.emt-config.properties
+EMT_MAIN_CONFIG=$EMT_DIR/.$OPENMRS_APP_NAME-emt-config.properties
 
 if [ ! -d $EMT_DIR ]; then
-mkdir $EMT_DIR
+	mkdir $EMT_DIR
 fi
 
 if [ ! -f $EMT_MAIN_CONFIG ]; then
-cat <<EOF > $EMT_MAIN_CONFIG
+	cat <<EOF > $EMT_MAIN_CONFIG
 openmrs_app_name=$OPENMRS_APP_NAME
 openmrs_data_directory=$OPENMRS_DATA_DIR
 openmrs_backups_directory=$OPENMRS_DATA_DIR/backups
 openmrs_url=$OPENMRS_URL
 EOF
-echo ""
-echo "INFO: You can change the provided configurations by editing: $EMT_MAIN_CONFIG";
-echo ""
+	echo ""
+	echo "INFO: You can change the provided configurations by editing: $EMT_MAIN_CONFIG";
+	echo ""
 fi
 
 OMRS_APP_NAME=`sed '/^\#/d' "$EMT_MAIN_CONFIG" | grep 'openmrs_app_name' | tail -n 1 | cut -d "=" -f2-`
@@ -38,19 +38,19 @@ OMRS_DATA_DIR=`sed '/^\#/d' "$EMT_MAIN_CONFIG" | grep 'openmrs_data_directory' |
 OMRS_BACKUP_DIR=`sed '/^\#/d' "$EMT_MAIN_CONFIG" | grep 'openmrs_backups_directory' | tail -n 1 | cut -d "=" -f2-`
 OMRS_URL=`sed '/^\#/d' "$EMT_MAIN_CONFIG" | grep 'openmrs_url' | tail -n 1 | cut -d "=" -f2-`
 if [ -f pom.xml ]; then
-EMR_MODULE_ID=`grep -m 1 '<artifactId>' pom.xml | cut -f2 -d">"|cut -f1 -d"<"`
-EMR_MODULE_VERSION=`grep -m 1 '<version>' pom.xml | cut -f2 -d">"|cut -f1 -d"<"`
-EMR_JAR=omod/target/$EMR_MODULE_ID-$EMR_MODULE_VERSION.jar
-cp $EMR_JAR $EMT_DIR/lib
+	EMR_MODULE_ID=`grep -m 1 '<artifactId>' pom.xml | cut -f2 -d">"|cut -f1 -d"<"`
+	EMR_MODULE_VERSION=`grep -m 1 '<version>' pom.xml | cut -f2 -d">"|cut -f1 -d"<"`
+	EMR_JAR=omod/target/$EMR_MODULE_ID-$EMR_MODULE_VERSION.jar
+	cp $EMR_JAR $EMT_DIR/lib
 fi
 cp -r shell-backend/lib $EMT_DIR
 cp shell-backend/*.sh $EMT_DIR
 if [ ! -d $OMRS_DATA_DIR ]; then
-echo "ERROR: $OMRS_DATA_DIR must exist to proceed, confirm that it is the right OpenMRS Data Directory/folder"
-exit 1
+	echo "ERROR: $OMRS_DATA_DIR must exist to proceed, confirm that it is the right OpenMRS Data Directory/folder"
+	exit 1
 fi
 if [ ! -d $OMRS_DATA_DIR/EmrMonitoringTool ]; then
-mkdir $OMRS_DATA_DIR/EmrMonitoringTool
+	mkdir $OMRS_DATA_DIR/EmrMonitoringTool
 fi
 bash $EMT_DIR/configure.sh $EMT_DIR $OMRS_DATA_DIR
 bash $EMT_DIR/startup-hook.sh
